//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSystem.Resources.Instruments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSystem.Resources.Instruments.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description can contain a maximum of 50 characters.
        /// </summary>
        public static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal member role is required for this view.
        /// </summary>
        public static string InsufficientSecurityClearance {
            get {
                return ResourceManager.GetString("InsufficientSecurityClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manufacturer is required for the instrument.
        /// </summary>
        public static string ManufacturerRequired {
            get {
                return ResourceManager.GetString("ManufacturerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manufacturer can contain a maximum of 50 characters.
        /// </summary>
        public static string ManufacturerTooLong {
            get {
                return ResourceManager.GetString("ManufacturerTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model number is required for the instrument.
        /// </summary>
        public static string ModelNoRequired {
            get {
                return ResourceManager.GetString("ModelNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model number can contain a maximum of 50 characters.
        /// </summary>
        public static string ModelNoTooLong {
            get {
                return ResourceManager.GetString("ModelNoTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no instruments.
        /// </summary>
        public static string NoInstruments {
            get {
                return ResourceManager.GetString("NoInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range can contain a maximum of 50 characters.
        /// </summary>
        public static string RangeTooLong {
            get {
                return ResourceManager.GetString("RangeTooLong", resourceCulture);
            }
        }
    }
}
