//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSystem.Resources.QuoteItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSystem.Resources.QuoteItems.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manager role is required to create a quote.
        /// </summary>
        public static string InsufficientSecurity {
            get {
                return ResourceManager.GetString("InsufficientSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calibration must be greater than 0.
        /// </summary>
        public static string InvalidCalibration {
            get {
                return ResourceManager.GetString("InvalidCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carriage must be greater than 0.
        /// </summary>
        public static string InvalidCarriage {
            get {
                return ResourceManager.GetString("InvalidCarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The days must be greater than 0.
        /// </summary>
        public static string InvalidDays {
            get {
                return ResourceManager.GetString("InvalidDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The investigation must be greater than 0.
        /// </summary>
        public static string InvalidInvestigation {
            get {
                return ResourceManager.GetString("InvalidInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The labour must be greater than 0.
        /// </summary>
        public static string InvalidLabour {
            get {
                return ResourceManager.GetString("InvalidLabour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parts must be greater than 0.
        /// </summary>
        public static string InvalidParts {
            get {
                return ResourceManager.GetString("InvalidParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report cannot exceed 2000 characters.
        /// </summary>
        public static string InvalidReport {
            get {
                return ResourceManager.GetString("InvalidReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job item is already pending quotation.
        /// </summary>
        public static string PendingItemExists {
            get {
                return ResourceManager.GetString("PendingItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quote item cannot be raised for this job item because its job is pending approval..
        /// </summary>
        public static string PendingJob {
            get {
                return ResourceManager.GetString("PendingJob", resourceCulture);
            }
        }
    }
}
