//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSystem.Resources.CompanyDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSystem.Resources.CompanyDetails.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address line cannot exceed 255 characters.
        /// </summary>
        public static string AddressLineTooLarge {
            get {
                return ResourceManager.GetString("AddressLineTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address must be supplied for the company.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company email address cannot exceed 50 characters.
        /// </summary>
        public static string EmailTooLarge {
            get {
                return ResourceManager.GetString("EmailTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fax number must be supplied for the company.
        /// </summary>
        public static string FaxRequired {
            get {
                return ResourceManager.GetString("FaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fax cannot exceed 50 characters.
        /// </summary>
        public static string FaxTooLarge {
            get {
                return ResourceManager.GetString("FaxTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required for the company.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name cannot exceed 255 characters.
        /// </summary>
        public static string NameTooLarge {
            get {
                return ResourceManager.GetString("NameTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company registration number cannot exceed 50 characters.
        /// </summary>
        public static string RegNoTooLarge {
            get {
                return ResourceManager.GetString("RegNoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A telephone number must be supplied for the company.
        /// </summary>
        public static string TelephoneRequired {
            get {
                return ResourceManager.GetString("TelephoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone cannot exceed 50 characters.
        /// </summary>
        public static string TelephoneTooLarge {
            get {
                return ResourceManager.GetString("TelephoneTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions must be supplied for the company.
        /// </summary>
        public static string TermsAndConditionsRequired {
            get {
                return ResourceManager.GetString("TermsAndConditionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terms and conditions cannot exceed 2000 characters.
        /// </summary>
        public static string TermsAndConditionsTooLarge {
            get {
                return ResourceManager.GetString("TermsAndConditionsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company VAT registration number cannot exceed 50 characters.
        /// </summary>
        public static string VatRegNoTooLarge {
            get {
                return ResourceManager.GetString("VatRegNoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL must be supplied for the company.
        /// </summary>
        public static string WwwRequired {
            get {
                return ResourceManager.GetString("WwwRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company URL cannot exceed 50 characters.
        /// </summary>
        public static string WwwTooLarge {
            get {
                return ResourceManager.GetString("WwwTooLarge", resourceCulture);
            }
        }
    }
}
