//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSystem.Resources.Customers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSystem.Resources.Customers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address line cannot exceed 50 characters.
        /// </summary>
        public static string AddressLineTooLarge {
            get {
                return ResourceManager.GetString("AddressLineTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset line cannot exceed 255 characters.
        /// </summary>
        public static string AssetLineTooLarge {
            get {
                return ResourceManager.GetString("AssetLineTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact information cannot exceed 50 characters.
        /// </summary>
        public static string ContactInfoTooLarge {
            get {
                return ResourceManager.GetString("ContactInfoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery title cannot exceed 255 characters.
        /// </summary>
        public static string DeliveryTitleTooLarge {
            get {
                return ResourceManager.GetString("DeliveryTitleTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer with this name already exists.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member role is required to perform this operation.
        /// </summary>
        public static string InsufficientSecurityClearance {
            get {
                return ResourceManager.GetString("InsufficientSecurityClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice title cannot exceed 255 characters.
        /// </summary>
        public static string InvoiceTitleTooLarge {
            get {
                return ResourceManager.GetString("InvoiceTitleTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required for the customer.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer name cannot exceed 255 characters.
        /// </summary>
        public static string NameTooLarge {
            get {
                return ResourceManager.GetString("NameTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least an internal member to view a customer.
        /// </summary>
        public static string ViewCustomerInsufficientSecurityClearance {
            get {
                return ResourceManager.GetString("ViewCustomerInsufficientSecurityClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least an internal member to view the customer list.
        /// </summary>
        public static string ViewCustomerListInsufficientSecurityClearance {
            get {
                return ResourceManager.GetString("ViewCustomerListInsufficientSecurityClearance", resourceCulture);
            }
        }
    }
}
