//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSystem.Resources.UserAccounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSystem.Resources.UserAccounts.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is not currently active..
        /// </summary>
        public static string AccountInactiveError {
            get {
                return ResourceManager.GetString("AccountInactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is currently locked out..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add a user to an archived Organisational Unit. .
        /// </summary>
        public static string ArchivedOrganisationUnit {
            get {
                return ResourceManager.GetString("ArchivedOrganisationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match..
        /// </summary>
        public static string ConfirmPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;strong&gt;{0}&lt;/strong&gt; available user accounts (currently using {1} of the total {2} available)..
        /// </summary>
        public static string CurrentUserLicenseUsageAndLimit {
            get {
                return ResourceManager.GetString("CurrentUserLicenseUsageAndLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. .
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details have been changed successfully..
        /// </summary>
        public static string DetailsChangedSuccessfully {
            get {
                return ResourceManager.GetString("DetailsChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you provided is associated with an existing account..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user account with the email address {0} already exists..
        /// </summary>
        public static string DuplicateEmailTemplate {
            get {
                return ResourceManager.GetString("DuplicateEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EMailAddressRequired {
            get {
                return ResourceManager.GetString("EMailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered has already been used..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is invalid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is too large. It must be less than 256 characters..
        /// </summary>
        public static string EmailTooLarge {
            get {
                return ResourceManager.GetString("EmailTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characters entered do not match those in the picture.
        /// </summary>
        public static string InvalidCaptchaEntered {
            get {
                return ResourceManager.GetString("InvalidCaptchaEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid List item selected..
        /// </summary>
        public static string InvalidOrganisationUnit {
            get {
                return ResourceManager.GetString("InvalidOrganisationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password entered. The password must be at least 8 characters long and contain at least 1 number. .
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least 8 characters and contain at least 1 number..
        /// </summary>
        public static string InvalidPasswordEntered {
            get {
                return ResourceManager.GetString("InvalidPasswordEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone specified was invalid..
        /// </summary>
        public static string InvalidTimeZoneId {
            get {
                return ResourceManager.GetString("InvalidTimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job title is required for the user.
        /// </summary>
        public static string JobTitleRequired {
            get {
                return ResourceManager.GetString("JobTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job title cannot exceed 256 characters.
        /// </summary>
        public static string JobTitleTooLarge {
            get {
                return ResourceManager.GetString("JobTitleTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence for this account has expired..
        /// </summary>
        public static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password was incorrect..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more active user accounts than your license allows. Archive users to recude the number of active accounts to continue..
        /// </summary>
        public static string MaxLicencedUsersExceededAdminUserMustFix {
            get {
                return ResourceManager.GetString("MaxLicencedUsersExceededAdminUserMustFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user as the new user would exceed the maximum number of licenced users..
        /// </summary>
        public static string MaxLicencedUsersExceededCreateUser {
            get {
                return ResourceManager.GetString("MaxLicencedUsersExceededCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import user as the user would exceed the maximum number of licenced users..
        /// </summary>
        public static string MaxLicencedUsersExceededImportUser {
            get {
                return ResourceManager.GetString("MaxLicencedUsersExceededImportUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of licensed users has been exceeded, therefore login has been disabled. Please contact a Risk Admin to reduce the number of active users..
        /// </summary>
        public static string MaxLicencedUsersExceededLogin {
            get {
                return ResourceManager.GetString("MaxLicencedUsersExceededLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reinstate user as the reinstated user would exceed the maximum number of licenced users..
        /// </summary>
        public static string MaxLicencedUsersExceededReinstateUser {
            get {
                return ResourceManager.GetString("MaxLicencedUsersExceededReinstateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must change your password before continuing.
        /// </summary>
        public static string MustChangePassword {
            get {
                return ResourceManager.GetString("MustChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the name must be between 1 and 255 characters.
        /// </summary>
        public static string NameInvalid {
            get {
                return ResourceManager.GetString("NameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one number..
        /// </summary>
        public static string NewPasswordDoesNotMeetMinimumRequirements {
            get {
                return ResourceManager.GetString("NewPasswordDoesNotMeetMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have no record of this email address..
        /// </summary>
        public static string NoUserExists {
            get {
                return ResourceManager.GetString("NoUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users were found. .
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully. .
        /// </summary>
        public static string PasswordChangeSuccessful {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered in the new and confirm passwords fields do not match..
        /// </summary>
        public static string PasswordConfirmationDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is incorrect..
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully..
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, please enter your email address in the field below..
        /// </summary>
        public static string ResetPasswordHelp {
            get {
                return ResourceManager.GetString("ResetPasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has not been assigned a role..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a name from the typeahead. Do you want to.
        /// </summary>
        public static string TextInputEmailOption {
            get {
                return ResourceManager.GetString("TextInputEmailOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been archived successfully..
        /// </summary>
        public static string UserArchivedSuccessfullyTemplate {
            get {
                return ResourceManager.GetString("UserArchivedSuccessfullyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account has been created successfully..
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s account has been edited successfully..
        /// </summary>
        public static string UserEditedSuccessfullyTemplate {
            get {
                return ResourceManager.GetString("UserEditedSuccessfullyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been reinstated successfully..
        /// </summary>
        public static string UserReinstatedSuccessfullyTemplate {
            get {
                return ResourceManager.GetString("UserReinstatedSuccessfullyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user currently has access to risks that have a higher security clearance than that set. Please remove the user&apos;s access to these risks..
        /// </summary>
        public static string UserSecurityClearanceTooLow {
            get {
                return ResourceManager.GetString("UserSecurityClearanceTooLow", resourceCulture);
            }
        }
    }
}
