//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSystem.Resources.UserAccounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSystem.Resources.UserAccounts.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Archived.
        /// </summary>
        public static string UserAccountArchivedEvent {
            get {
                return ResourceManager.GetString("UserAccountArchivedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Created.
        /// </summary>
        public static string UserAccountCreatedEvent {
            get {
                return ResourceManager.GetString("UserAccountCreatedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Edited.
        /// </summary>
        public static string UserAccountEditedEvent {
            get {
                return ResourceManager.GetString("UserAccountEditedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Gael Risk account was edited by {0} on {1} UTC:
        ///
        ///{2}
        ///
        ///You can view the record by visiting: {3}.
        /// </summary>
        public static string UserAccountEditedTemplate {
            get {
                return ResourceManager.GetString("UserAccountEditedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Reinstated.
        /// </summary>
        public static string UserAccountReinstatedEvent {
            get {
                return ResourceManager.GetString("UserAccountReinstatedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},
        ///A Gael Risk account ({1}) has been reinstated by your Risk Administrator ({2}, {3}).
        ///You can access Gael Risk by visiting {4}.
        /// </summary>
        public static string UserAccountReinstatedTemplate {
            get {
                return ResourceManager.GetString("UserAccountReinstatedTemplate", resourceCulture);
            }
        }
    }
}
